# -*- coding: utf-8 -*-
"""Code lần 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSKSWK_iCi7OYyzevFNyi4ksEhCtYpU6

# Phần 1: Chọn mô hình

#1.Import thư viện
"""

# !pip install pandas numpy matplotlib seaborn lifetimes scikit-learn xgboost tqdm
!pip install lifetimes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta


from lifetimes import BetaGeoFitter, GammaGammaFitter
from lifetimes.utils import summary_data_from_transaction_data


from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor, XGBClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, roc_auc_score, average_precision_score


import warnings
warnings.filterwarnings('ignore')


sns.set_style('whitegrid')
plt.rcParams['figure.dpi']=120

"""#2.Load Data"""

from google.colab import drive
drive.mount('/content/drive')

customers = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_customers_dataset.csv")
orders = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_orders_dataset.csv")
items = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_order_items_dataset.csv")
payments = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_order_payments_dataset.csv")
reviews = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_order_reviews_dataset.csv")
#geo = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_geolocation_dataset.csv")
#product = pd.read_csv("/content/drive/MyDrive/KLTN - Dataset/olist_products_dataset.csv")

# Kiểm tra nhanh kích thước và cột
print(customers.shape, orders.shape, items.shape, payments.shape, reviews.shape)
orders.head(3)

"""## 2.1. Table orders"""

orders.head(4)

orders.info()

#Tạo funtion để tính tỉ lệ giá trị bị null trong các hàng
def calc_null_rate(df):
  newdf=df.isnull().sum().to_frame('null_count')
  newdf[['null_rate']]=newdf[['null_count']]/len(df)
  return newdf.sort_values(by=['null_rate'],ascending=False)

calc_null_rate(orders)

"""* Nhận xét: 3 cột đầu tiên có giá trị null nhưng phần phân tích phía dưới không dùng nên sẽ lược bỏ"""

orders['order_status'].value_counts(normalize=True) * 100

"""* Lưu ý: Ở phần phân tích phía sau, chỉ giữ lại các đơn hàng đã có trạng thái chuyển "delivered"

## 2.2. Table items
"""

items.head(4)

items.head(4)

items.info()

calc_null_rate(items)

items['order_id'].nunique()

"""Nhận xét: Vì mỗi đơn hàng có nhiều order_item khác nhau"""

items.describe()

"""+ Nhận xét: Cột price và freight value không xuất hiện giá trị âm => Phù hợp"""

# Kiểm tra tỷ lệ freight_value = 0
zero_freight = (items['freight_value'] == 0).sum()
total_rows = len(items)
print(f"Số dòng freight_value = 0: {zero_freight} ({zero_freight/total_rows*100:.2f}%)")

"""+ Nhận xét: Có thể đây là những đơn hàng freeship nên giá trị vận chuyển = 0 là bình thường

## 2.3. Table customers
"""

customers.head(4)

customers.info()

customers['customer_id'].nunique()

customers['customer_unique_id'].nunique()

"""* Nhận xét:
  + Có 99,441 đơn hàng được gán cho 96,096 khách hàng thực tế
  → Tức là chỉ khoảng 3,345 khách hàng đã mua từ 2 lần trở lên
"""

repeat_customers = (
    customers.groupby('customer_unique_id')['customer_id']
    .nunique()
    .reset_index(name='order_count')
)

repeat_customers['is_repeat'] = repeat_customers['order_count'] > 1
repeat_customers['is_repeat'].value_counts(normalize=True) * 100

"""→ Nghĩa là khoảng 3.12% khách hàng thực đã mua nhiều hơn 1 lần và gần 97% khách hàng chỉ mua 1 lần duy nhất"""

# Check qua số khách hàng ở mỗi tháng

# Gộp 2 bảng qua khóa customer_id
orders_cust = orders.merge(customers, on='customer_id', how='left')

# Chuyển cột thời gian sang datetime
orders_cust['order_date'] = pd.to_datetime(orders_cust['order_purchase_timestamp'])

# Tạo cột tháng
orders_cust['order_month'] = orders_cust['order_date'].dt.to_period('M')

# Tính số khách hàng unique mỗi tháng (dựa trên customer_unique_id)
unique_users_by_month = (
    orders_cust.groupby('order_month')['customer_unique_id']
    .nunique()
    .reset_index()
    .rename(columns={'customer_unique_id': 'n_unique_users'})
)

# Chuyển order_month về dạng timestamp
unique_users_by_month['order_month'] = unique_users_by_month['order_month'].dt.to_timestamp()

# In kết quả
print(unique_users_by_month.head(30))

"""* Nhận xét: Mặc dù Dataset từ 9/2016 - 10/2018, tuy nhiên bị thiếu dữ liệu của tháng 11/2016, đồng thời số khách hàng của tháng 9,10,12 năm 2016 và tháng 9,10 của năm 2018 rất nhỏ
  * Vì thế, bài phân tích chỉ tập trung vào khoảng 1/2017 đến 6/2018

#3.Gộp bảng và lọc điều kiện
"""

# Giữ đơn đã giao thành công
orders = orders[orders['order_status'] == 'delivered'].copy()
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'], errors='coerce')

# Tính giá trị đơn hàng = price + freight_value
items['order_value'] = items['price'] + items['freight_value']
order_val = items.groupby('order_id', as_index=False)['order_value'].sum()

# Merge bảng giao dịch cơ bản (1 dòng = 1 order)
trans = (
    orders[['order_id', 'customer_id', 'order_purchase_timestamp']]
    .merge(order_val, on='order_id', how='left')
    .merge(customers[['customer_id', 'customer_unique_id', 'customer_state']], on='customer_id', how='left')
    .rename(columns={'order_purchase_timestamp': 'order_date'})
    [['order_id', 'customer_unique_id', 'order_date', 'order_value', 'customer_state']]
    .dropna()
    .drop_duplicates()
)
trans['order_date'] = pd.to_datetime(trans['order_date'], errors='coerce')

# Giữ lại dữ liệu từ 01/01/2017 trở đi
trans = trans[trans['order_date'] >= '2017-01-01']
print("Tổng số giao dịch:", len(trans))
trans.head(3)

trans.info()

calc_null_rate(trans)

"""#4.EDA (phân phối & đặc điểm dữ liệu)"""

plt.figure(figsize=(8,4))
sns.histplot(trans['order_value'], bins=80, log_scale=True)
plt.title("Phân bố giá trị đơn hàng (log scale)")
plt.xlabel("Order Value (log)")
plt.ylabel("Số lượng"); plt.show()

# Phân phối số đơn theo khách
cust_orders = trans.groupby('customer_unique_id')['order_id'].nunique()
sns.histplot(cust_orders, bins=40)
plt.title("Số đơn hàng mỗi khách"); plt.xlabel("Số đơn"); plt.show()
print("Tỷ lệ khách chỉ mua 1 lần:", (cust_orders.eq(1).mean()*100).round(2), "%")

# Tỷ trọng phương thức thanh toán
pm = payments.merge(orders[['order_id']], on='order_id', how='inner')
share = pm['payment_type'].value_counts(normalize=True).head(6)
share.plot(kind='bar', figsize=(8,4))
plt.title("Tỷ trọng phương thức thanh toán (Top)"); plt.ylabel("Tỷ lệ"); plt.show()

"""#5.Tách thời gian (Cutoff & Horizon) + Chia Train/Test"""

# Thiết lập mốc thời gian tách dữ liệu (temporal split)
# - CUTOFF: mốc tách train/test (31/12/2017)
# - H_START, H_END: giai đoạn dự báo CLV (01/2018–06/2018)
# - SNAPSHOT: điểm tham chiếu tính Recency
CUTOFF  = pd.Timestamp('2017-12-31')
H_START = CUTOFF + pd.Timedelta(days=1)
H_END   = H_START + pd.DateOffset(months=6)
SNAPSHOT = CUTOFF + pd.Timedelta(days=1)

# Chia dữ liệu:
# - train_tx: giao dịch trước cutoff (dùng huấn luyện)
# - test_tx : giao dịch sau cutoff (dùng đánh giá CLV thực tế)
train_tx = trans[trans['order_date'] <= CUTOFF].copy()
test_tx  = trans[(trans['order_date'] > CUTOFF) & (trans['order_date'] <= H_END)].copy()

# ⚠️ Lưu ý: Khách hàng chỉ xuất hiện sau cutoff (cold-start) sẽ bị loại tự động
# vì không có lịch sử trong train_tx → không thể dự báo CLV
print("Train orders:", len(train_tx), "| Test (horizon):", len(test_tx))

# Minh họa trực quan Cutoff & Horizon
plt.figure(figsize=(10,2))
plt.axvline(CUTOFF, color='r', linestyle='--', label='Cutoff (31/12/2017)')
plt.axvspan(train_tx['order_date'].min(), CUTOFF, color='lightblue', alpha=0.5, label='Train')
plt.axvspan(H_START, H_END, color='lightgreen', alpha=0.4, label='Horizon 6M')
plt.title("Minh họa tách thời gian (Cutoff & Horizon)")
plt.legend(); plt.tight_layout(); plt.show()

train_tx['customer_unique_id'].nunique()

train_tx.info()

"""#6.Tính RFM (Recency–Frequency–Monetary)"""

rfm = (
    train_tx.groupby('customer_unique_id')
    .agg(last=('order_date', 'max'),
         first=('order_date', 'min'),
         num=('order_id', 'nunique'),
         spent=('order_value', 'sum'))
)
rfm['recency']   = (SNAPSHOT - rfm['last']).dt.days
rfm['T']         = (SNAPSHOT - rfm['first']).dt.days
rfm['frequency'] = rfm['num'] - 1
rfm['monetary']  = rfm['spent'] / rfm['num']

rfm_simple = rfm[['recency', 'frequency', 'monetary']].reset_index()
print("Số khách hàng:", len(rfm_simple))
rfm_simple.head(3)

import pandas as pd, numpy as np, matplotlib.pyplot as plt

# Nhóm frequency thành 5 mức: 0,1,2,3,>4
bins = [-1, 0, 1, 2, 3, np.inf]
labels = ['0', '1', '2', '3', '>4']
rfm_simple['freq_group'] = pd.cut(rfm_simple['frequency'], bins=bins, labels=labels)

# Đếm số khách hàng và tỷ lệ %
freq_summary = (
    rfm_simple['freq_group']
    .value_counts()
    .sort_index()
    .reset_index()
    .rename(columns={'index': 'frequency_group', 'freq_group': 'count'})  # sửa ở đây
)

# 🛠️ Sửa tên đúng của cột đếm
freq_summary.columns = ['frequency_group', 'count']

# Ép kiểu sang int
freq_summary['count'] = freq_summary['count'].astype(int)

# Thêm cột % khách hàng
freq_summary['percent'] = (freq_summary['count'] / freq_summary['count'].sum() * 100).round(2)

print("\n📊 Phân phối tần suất mua hàng (Frequency):")
print(freq_summary.to_string(index=False))

# (Tùy chọn) Vẽ biểu đồ
plt.figure(figsize=(6,3))
plt.bar(freq_summary['frequency_group'], freq_summary['count'], color='#42A5F5')
plt.xlabel("Số lần mua (Frequency)")
plt.ylabel("Số khách hàng")
plt.title("Phân phối tần suất mua hàng (Train set)")
for i, v in enumerate(freq_summary['count']):
    plt.text(i, v + 5, f"{freq_summary['percent'][i]}%", ha='center', fontsize=9)
plt.tight_layout()
plt.show()

"""# Thêm"""

# 2️⃣ Tính RFM không trừ 1 (dùng cho phân tích hành vi)
rfm_nominus = (
    train_tx.groupby('customer_unique_id')
    .agg(last=('order_date', 'max'),
         first=('order_date', 'min'),
         num=('order_id', 'nunique'),
         spent=('order_value', 'sum'))
)

rfm_nominus['recency']   = (SNAPSHOT - rfm_nominus['last']).dt.days
rfm_nominus['T']         = (SNAPSHOT - rfm_nominus['first']).dt.days
rfm_nominus['frequency'] = rfm_nominus['num']      # không trừ 1
rfm_nominus['monetary']  = rfm_nominus['spent'] / rfm_nominus['num']

rfm_nominus = rfm_nominus[['recency', 'frequency', 'T', 'monetary']].reset_index()
rfm_nominus['type'] = 'RFM_raw'

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(12,5))

sns.histplot(rfm_nominus['frequency'], bins=30, ax=axes[0], color='skyblue', kde=True)
axes[0].set_title("Frequency (không trừ 1)")

sns.histplot(rfm_std['frequency'], bins=30, ax=axes[1], color='salmon', kde=True)
axes[1].set_title("Frequency (trừ 1)")

for ax in axes:
    ax.set_xlabel("Frequency")
    ax.set_ylabel("Số khách hàng")

plt.suptitle("So sánh phân phối Frequency giữa hai cách tính RFM", fontsize=13)
plt.tight_layout()
plt.show()

"""#7.Cohort Retention"""

train_tx['order_month'] = train_tx['order_date'].dt.to_period('M')
first_month = train_tx.groupby('customer_unique_id')['order_month'].min().rename('cohort')
cohort_df = train_tx.merge(first_month, on='customer_unique_id', how='left')
cohort_df['cohort_index'] = (cohort_df['order_month'] - cohort_df['cohort']).apply(lambda p: p.n)

cohort_pivot = (
    cohort_df.groupby(['cohort', 'cohort_index'])['customer_unique_id']
    .nunique().unstack(1).fillna(0)
)
retention = cohort_pivot.divide(cohort_pivot.iloc[:,0], axis=0)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

# Bỏ cột 0 (tháng đầu = 100%)
sns.heatmap(
    retention.iloc[:, 1:13],    # chỉ lấy từ tháng 1 đến tháng 12
    annot=True,
    fmt=".2%",
    cmap="YlGnBu",
    cbar=True
)

plt.title("Cohort Retention (Train-only) — 12 tháng đầu (ẩn cột 100%)", fontsize=13)
plt.ylabel("Cohort theo tháng đầu")
plt.xlabel("Tháng kể từ tháng đầu tiên")
plt.show()

"""* Nhận xét tổng quan:
  - Tỷ lệ quay lại nhìn chung rất thấp, chỉ dao động quanh 0.2–0.7% ở tháng kế tiếp, rồi giảm nhanh về gần 0% sau 3–4 tháng.

  - Đa số cohort đều có hiện tượng “rơi rụng nhanh”, đặc biệt từ tháng thứ 4 trở đi, gần như không còn khách quay lại.

  - Điều này cho thấy phần lớn khách hàng chỉ phát sinh một lần mua, đúng với mô tả “one-time heavy” thường thấy trong thương mại điện tử marketplace.

#8.Baseline CLV – Fit BG/NBD & Gamma–Gamma (Feature Engineering II)
"""

from lifetimes import BetaGeoFitter, GammaGammaFitter
from lifetimes.utils import summary_data_from_transaction_data

# Tạo bảng tóm tắt hành vi mua (input cho lifetimes)
summary = summary_data_from_transaction_data(
    transactions=train_tx,
    customer_id_col='customer_unique_id',
    datetime_col='order_date',
    monetary_value_col='order_value',
    observation_period_end=SNAPSHOT,
    freq='D'
).reset_index()

# Fit mô hình BG/NBD (tần suất mua)
bgf = BetaGeoFitter(penalizer_coef=0.001)
bgf.fit(summary['frequency'], summary['recency'], summary['T'])

# Fit mô hình Gamma–Gamma (chi tiêu trung bình)
mask_rep = (summary['frequency'] > 0) & (summary['monetary_value'] > 0)
ggf = GammaGammaFitter(penalizer_coef=0.001)
ggf.fit(summary.loc[mask_rep,'frequency'], summary.loc[mask_rep,'monetary_value'])

# Dự báo số lần mua và chi tiêu trong 6 tháng tới
H_days = (H_END - H_START).days + 1
summary['pred_purchases_6m'] = bgf.predict(H_days, summary['frequency'], summary['recency'], summary['T'])
summary['pred_avg_value']    = ggf.conditional_expected_average_profit(summary['frequency'], summary['monetary_value'])
summary['CLV_prob_6m']       = summary['pred_purchases_6m'] * summary['pred_avg_value']

# Xác suất còn hoạt động
summary['p_alive'] = bgf.conditional_probability_alive(summary['frequency'], summary['recency'], summary['T'])

# Biểu đồ phân phối CLV dự báo
plt.figure(figsize=(8,4))
sns.histplot(summary['CLV_prob_6m'], bins=60, kde=True)
plt.title('Phân bố CLV dự báo (BG/NBD + Gamma–Gamma)')
plt.xlabel('CLV_prob_6m'); plt.show()

"""* Nhận xét:
  - Phân phối CLV dự báo (BG/NBD + Gamma–Gamma) cho thấy giá trị rất lệch phải, phần lớn khách hàng có CLV thấp trong khi chỉ một số ít có giá trị cao vượt trội --> Phản ánh sự tập trung giá trị trong nhóm nhỏ khách hàng
"""

import matplotlib.ticker as mtick

# --- Biểu đồ 1: Toàn bộ phân phối CLV (log scale để xử lý heavy-tail) ---
plt.figure(figsize=(8,4))
sns.histplot(summary['CLV_prob_6m'], bins=80, kde=True, color='#66b3ff', alpha=0.8)
plt.xscale('log')  # log scale giúp “nén” phần đuôi dài
plt.title('Phân bố CLV dự báo (BG/NBD + Gamma–Gamma) — log scale')
plt.xlabel('CLV_prob_6m (log scale)')
plt.ylabel('Số lượng khách hàng')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# --- Biểu đồ 2: Zoom phần CLV nhỏ (≤ 100) để xem rõ “phổ đầu” ---
plt.figure(figsize=(8,4))
sns.histplot(summary.loc[summary['CLV_prob_6m'] <= 100, 'CLV_prob_6m'],
             bins=40, kde=True, color='#ff9999', alpha=0.8)
plt.title('Phân bố CLV dự báo (BG/NBD + Gamma–Gamma) — Zoom ≤ 100')
plt.xlabel('CLV_prob_6m')
plt.ylabel('Số lượng khách hàng')
plt.grid(alpha=0.3)

# Thêm label top giá trị (như 0–20, 20–40,…)
plt.gca().xaxis.set_major_formatter(mtick.StrMethodFormatter('{x:,.0f}'))
plt.tight_layout()
plt.show()

# --- Thêm biểu đồ 3: Boxplot để thấy toàn cảnh “phân phối lệch” ---
plt.figure(figsize=(7,2))
sns.boxplot(x=summary['CLV_prob_6m'], color='#99c2ff')
plt.title('Boxplot CLV dự báo — thấy rõ outliers và phân phối lệch')
plt.xlabel('CLV_prob_6m')
plt.tight_layout()
plt.show()

"""#9.Gắn nhãn CLV thực tế & tạo Feature Set"""

# Nhãn thật (chi tiêu thực tế trong Horizon) - Horizon là 6 tháng đầu của 2018
y_true = (
    test_tx.groupby('customer_unique_id')['order_value'].sum()
    .rename('CLV_actual_6m')
)
summary = summary.merge(y_true, on='customer_unique_id', how='left')
summary['CLV_actual_6m'] = summary['CLV_actual_6m'].fillna(0.0)

# Bổ sung feature hành vi mở rộng (payment/review/items)
agg_base = train_tx[['order_id','customer_unique_id','customer_state']].copy()
feat_aggs = (
    agg_base
    .merge(payments[['order_id','payment_value']], on='order_id', how='left')
    .merge(reviews[['order_id','review_score']], on='order_id', how='left')
    .merge(items[['order_id','product_id']], on='order_id', how='left')
    .groupby('customer_unique_id')
    .agg(
        payment_value_sum   = ('payment_value','sum'),
        payment_value_mean  = ('payment_value','mean'),
        review_score_mean   = ('review_score','mean'),
        num_unique_products = ('product_id', pd.Series.nunique),
        state_mode          = ('customer_state', lambda x: x.mode()[0] if len(x.mode())>0 else np.nan)
    ).reset_index()
)

# Merge features vào bảng summary
summary_ml = summary.merge(feat_aggs, on='customer_unique_id', how='left')
summary_ml.head(5)

calc_null_rate(summary_ml)

# Xử lý thiếu
# Chỉ còn cột 'review_score_mean' bị thiếu (~0.7% khách)
# Điền giá trị trung vị để giữ phân phối ổn định, tránh mất mẫu
median_review = summary_ml['review_score_mean'].median()
summary_ml['review_score_mean'] = summary_ml['review_score_mean'].fillna(median_review)

print("Tổng số khách hàng:", len(summary_ml))
summary_ml.head(3)

"""#10.Tạo Preprocessor và 3 Pipeline Ứng viên"""

from sklearn.model_selection import KFold, cross_val_score

# Xác định cột numeric và categorical
numeric_features = [
    'frequency','recency','T','monetary_value',
    'p_alive','CLV_prob_6m',
    'payment_value_sum','payment_value_mean',
    'review_score_mean','num_unique_products'
]
categorical_features = ['state_mode']

# Preprocessor: scale số + OneHotEncode hạng mục
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# Chuẩn bị tập X, y
X_final = summary_ml[numeric_features + categorical_features].copy()
y_final = summary_ml['CLV_actual_6m'].astype(float).copy()

# Định nghĩa 3 mô hình
models = {
    "LinearRegression": LinearRegression(),
    "RandomForest": RandomForestRegressor(n_estimators=400, max_depth=12, random_state=42),
    "XGBoost": XGBRegressor(
        n_estimators=700, learning_rate=0.05, max_depth=6,
        subsample=0.8, colsample_bytree=0.8, tree_method='hist', random_state=42
    )
}

# Tạo Pipeline cho từng model
from sklearn.pipeline import Pipeline
pipelines = {
    name: Pipeline([('preprocess', preprocessor), ('model', model)])
    for name, model in models.items()
}

"""#11.Cross-Validation & Lựa chọn Mô hình Tốt nhất

## 11.1 So sánh mô hình trên toàn bộ tập train
  * Mục đích:

    - Chạy 3 mô hình khác nhau (Linear, RF, XGB) trên cùng dữ liệu.

    - Đo lường độ khớp (fit) trên tập huấn luyện (X_final, y_final).

    - Giúp so sánh nhanh mô hình nào có hiệu năng tổng thể tốt hơn trước khi đi vào đánh giá chính thức.
"""

for model_name in ["LinearRegression", "RandomForest", "XGBoost"]:
    pipe = pipelines[model_name]
    pipe.fit(X_final, y_final)
    y_pred = pipe.predict(X_final)
    print(f"{model_name} → MAE={mean_absolute_error(y_final, y_pred):.3f}, "
          f"RMSE={np.sqrt(mean_squared_error(y_final, y_pred)):.3f}, "
          f"R²={r2_score(y_final, y_pred):.3f}")

"""* Nhận xét: Nhận thấy XGBoost cho MAE thấp hơn và R^2 cao nhất trong 3 cái

## 11.2 Kiểm định độ ổn định bằng Cross-Validation (CV)
* Mục tiêu: Đánh giá độ ổn định và khả năng tổng quát của mô hình
    * Thay vì dùng toàn bộ dữ liệu 1 lần, chia làm 3 phần (3-Fold CV):

        + mỗi lần 2 phần train, 1 phần test,

        + lặp lại 3 lần, lấy trung bình kết quả.
"""

pipe_lr = pipelines["LinearRegression"]

from sklearn.model_selection import KFold, cross_val_score
cv = KFold(n_splits=3, shuffle=True, random_state=42)

mae_scores  = -cross_val_score(pipe_lr, X_final, y_final, cv=cv, scoring='neg_mean_absolute_error')
rmse_scores = np.sqrt(-cross_val_score(pipe_lr, X_final, y_final, cv=cv, scoring='neg_mean_squared_error'))
r2_scores   = cross_val_score(pipe_lr, X_final, y_final, cv=cv, scoring='r2')

print("=== Linear Regression (3-Fold CV) ===")
print(f"MAE mean = {mae_scores.mean():.3f} ± {mae_scores.std():.3f}")
print(f"RMSE mean = {rmse_scores.mean():.3f} ± {rmse_scores.std():.3f}")
print(f"R² mean = {r2_scores.mean():.3f} ± {r2_scores.std():.3f}")

pipe_xgb = pipelines["XGBoost"]

from sklearn.model_selection import KFold, cross_val_score
cv = KFold(n_splits=3, shuffle=True, random_state=42)

mae_scores  = -cross_val_score(pipe_xgb, X_final, y_final, cv=cv, scoring='neg_mean_absolute_error')
rmse_scores = np.sqrt(-cross_val_score(pipe_xgb, X_final, y_final, cv=cv, scoring='neg_mean_squared_error'))
r2_scores   = cross_val_score(pipe_xgb, X_final, y_final, cv=cv, scoring='r2')

print("=== XGBoost (3-Fold CV) ===")
print(f"MAE mean = {mae_scores.mean():.3f} ± {mae_scores.std():.3f}")
print(f"RMSE mean = {rmse_scores.mean():.3f} ± {rmse_scores.std():.3f}")
print(f"R² mean = {r2_scores.mean():.3f} ± {r2_scores.std():.3f}")

pipe_rf = pipelines["RandomForest"].set_params(model__n_estimators=200)
 from sklearn.model_selection import KFold, cross_val_score
 cv = KFold(n_splits=3, shuffle=True, random_state=42)
 mae_scores = -cross_val_score(pipe_rf, X_final, y_final, cv=cv, scoring='neg_mean_absolute_error')
 rmse_scores = np.sqrt(-cross_val_score(pipe_rf, X_final, y_final, cv=cv, scoring='neg_mean_squared_error'))
 r2_scores = cross_val_score(pipe_rf, X_final, y_final, cv=cv, scoring='r2')
 print("=== Random Forest (3-Fold CV) ===")
 print(f"MAE mean = {mae_scores.mean():.3f} ± {mae_scores.std():.3f}")
 print(f"RMSE mean = {rmse_scores.mean():.3f} ± {rmse_scores.std():.3f}")
 print(f"R² mean = {r2_scores.mean():.3f} ± {r2_scores.std():.3f}")

"""### Tổng kết chọn mô hình:
+ Mô hình Linear Regression có sai số trung bình (MAE, RMSE) thấp nhất và ổn định nhất,
+ Trong khi Random Forest và XGBoost không mang lại cải thiện đáng kể về độ chính xác.
+ Tuy nhiên, do đặc trưng dữ liệu CLV phi tuyến và phân phối lệch mạnh, mô hình phi tuyến (XGBoost) vẫn được giữ lại như mô hình mở rộng để khai thác tiềm năng học tương tác giữa các đặc trưng.
    + Vì vậy, nghiên cứu lựa chọn Linear Regression làm baseline và XGBoost làm mô hình cuối cùng (final CLV model) cho giai đoạn phân tích, phân khúc và ứng dụng kết quả.

#12.Huấn luyện mô hình XGBoost Final
"""

from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

# --- Lấy lại preprocessor & cấu hình model tốt nhất ---
xgb_final = XGBRegressor(
    n_estimators=700,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method='hist',
    random_state=42
)

pipe_xgb_final = Pipeline([
    ('preprocess', preprocessor),
    ('model', xgb_final)
])

# --- Fit mô hình trên toàn bộ dữ liệu ---
print("Đang huấn luyện mô hình XGBoost FINAL trên toàn bộ dữ liệu ...")
pipe_xgb_final.fit(X_final, y_final)

# --- Lưu pipeline đã huấn luyện ---
joblib.dump(pipe_xgb_final, 'clv_pipeline_xgb.joblib')
print("Đã lưu mô hình pipeline tại: clv_pipeline_xgb.joblib")

"""#13.Dự báo CLV Final & Đánh giá"""

# Dự báo CLV cho toàn bộ khách hàng
y_pred_final = pipe_xgb_final.predict(X_final)

# Tính sai số & R²
mae_final  = mean_absolute_error(y_final, y_pred_final)
rmse_final = np.sqrt(mean_squared_error(y_final, y_pred_final))
r2_final   = r2_score(y_final, y_pred_final)

print("=== Kết quả mô hình XGBoost FINAL ===")
print(f"MAE = {mae_final:.3f}")
print(f"RMSE = {rmse_final:.3f}")
print(f"R² = {r2_final:.3f}")

"""#14.Phân tích tầm quan trọng đặc trưng (Feature Importance)"""

# --- Lấy tên cột sau khi qua preprocessor ---
# Lấy tên cột numeric
num_names = numeric_features

# Lấy tên cột OneHotEncode (categorical)
cat_names = list(
    pipe_xgb_final.named_steps['preprocess']
    .named_transformers_['cat']
    .get_feature_names_out(categorical_features)
)

# Gộp lại
all_feature_names = num_names + cat_names

# --- Lấy importance từ model ---
feature_importance = pipe_xgb_final.named_steps['model'].feature_importances_

# --- Tạo bảng importance ---
imp_df = pd.Series(feature_importance, index=all_feature_names).sort_values(ascending=True)

plt.figure(figsize=(8,6))
imp_df.tail(15).plot(kind='barh')   # chỉ hiển thị top 15 feature quan trọng
plt.title("Độ quan trọng của đặc trưng — XGBoost FINAL")
plt.xlabel("Feature Importance")
plt.tight_layout()
plt.show()

"""#15.So sánh thực tế vs dự báo & Phân khúc khách hàng"""

# Thêm vào bảng tổng hợp
summary_ml['CLV_pred_final'] = np.maximum(y_pred_final, 0)

# Vẽ scatter để so sánh
plt.figure(figsize=(6,6))
plt.scatter(y_final, y_pred_final, alpha=0.3)
lim = [0, max(y_final.max(), y_pred_final.max())]
plt.plot(lim, lim, 'r--', linewidth=1)
plt.xlim(lim); plt.ylim(lim)
plt.xlabel('CLV thực (6 tháng)')
plt.ylabel('CLV dự báo (XGBoost Final)')
plt.title('Thực tế vs Dự báo — XGBoost FINAL')
plt.tight_layout(); plt.show()

# --- Phân khúc theo quantile 33/66 ---
q33, q66 = np.quantile(summary_ml['CLV_pred_final'], [0.33, 0.66])

def seg(v):
    if v <= q33: return 'Low'
    elif v <= q66: return 'Mid'
    else: return 'High'

summary_ml['Segment'] = summary_ml['CLV_pred_final'].apply(seg)

# Thống kê từng phân khúc
seg_stats = summary_ml.groupby('Segment')['CLV_pred_final'].agg(['count','mean','sum']).sort_values('mean')
display(seg_stats)

# Boxplot CLV theo phân khúc
import seaborn as sns
plt.figure(figsize=(6,4))
sns.boxplot(x='Segment', y='CLV_pred_final', data=summary_ml, palette='coolwarm')
plt.title('Phân bố CLV dự báo theo phân khúc')
plt.tight_layout(); plt.show()

"""#16.Xuất CSV kết quả - 3 outputs"""

# --- Lưu output ---
OUT_DIR = './clv_outputs_final_xgb'
import os; os.makedirs(OUT_DIR, exist_ok=True)

out_pred = summary_ml[['customer_unique_id','p_alive','CLV_prob_6m',
                       'CLV_actual_6m','CLV_pred_final','Segment']]
out_pred.to_csv(f'{OUT_DIR}/customer_clv_predictions_xgb.csv', index=False)

seg_stats.to_csv(f'{OUT_DIR}/segment_stats_xgb.csv')

imp_df.sort_values(ascending=False).to_csv(f'{OUT_DIR}/xgb_feature_importance.csv')

print("Đã lưu toàn bộ kết quả vào thư mục:", OUT_DIR)

"""# Phần 2: Đưa ra Insights (dựa theo số liệu và biểu đồ in ra)"""

# Đường cong Pareto (Top 30% khách hàng tạo bao nhiêu % CLV)
srt = summary_ml.sort_values('CLV_pred_final', ascending=False).reset_index(drop=True)
srt['cum_customers'] = (np.arange(len(srt)) + 1) / len(srt)
srt['cum_value'] = srt['CLV_pred_final'].cumsum() / srt['CLV_pred_final'].sum()

plt.figure(figsize=(7,4))
plt.plot(srt['cum_customers'], srt['cum_value'], label='Pareto')
plt.axvline(0.3, color='r', linestyle='--', label='Top 30% KH')
plt.title('Đường cong Pareto — CLV dự báo (XGB Final)')
plt.xlabel('% khách hàng tích lũy')
plt.ylabel('% CLV tích lũy')
plt.legend(); plt.tight_layout(); plt.show()

# Top 10 khách hàng có CLV cao nhất
top10 = summary_ml.sort_values('CLV_pred_final', ascending=False).head(10)
display(top10[['customer_unique_id','CLV_pred_final','Segment']])

import matplotlib.pyplot as plt
import seaborn as sns

# --- Bar chart tổng CLV theo phân khúc ---
plt.figure(figsize=(7,4))
sns.barplot(x=seg_stats.index, y='sum', data=seg_stats.reset_index(),
            palette=['#FF9999', '#87CEFA', '#90EE90'])
plt.title('Tổng CLV dự báo theo phân khúc khách hàng')
plt.ylabel('Tổng CLV (6 tháng)')
plt.xlabel('Phân khúc')

# Hiển thị nhãn giá trị trên đầu cột
for i, v in enumerate(seg_stats['sum']):
    plt.text(i, v + seg_stats['sum'].max()*0.02, f"{v:,.0f}", ha='center', fontsize=10, fontweight='bold')

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# --- Bar chart trung bình CLV theo phân khúc ---
plt.figure(figsize=(7,4))
sns.barplot(x=seg_stats.index, y='mean', data=seg_stats.reset_index(),
            palette=['#FF9999', '#87CEFA', '#90EE90'])
plt.title('Giá trị CLV trung bình theo phân khúc khách hàng')
plt.ylabel('CLV trung bình (6 tháng)')
plt.xlabel('Phân khúc')

for i, v in enumerate(seg_stats['mean']):
    plt.text(i, v + seg_stats['mean'].max()*0.03, f"{v:,.0f}", ha='center', fontsize=10, fontweight='bold')

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# --- Pie chart thể hiện tỉ trọng tổng CLV ---
plt.figure(figsize=(6,6))
colors = ['#FF9999', '#87CEFA', '#90EE90']
plt.pie(seg_stats['sum'], labels=seg_stats.index, autopct='%1.1f%%',
        startangle=120, colors=colors, textprops={'fontsize':11})
plt.title('Tỷ trọng tổng CLV dự báo theo phân khúc')
plt.tight_layout()
plt.show()

import pandas as pd, numpy as np, matplotlib.pyplot as plt

# Đọc dữ liệu dự báo CLV
out_pred = pd.read_csv(f"{OUT_DIR}/customer_clv_predictions_xgb.csv")

# Tính phân phối Pareto
clv = out_pred["CLV_pred_final"].clip(lower=0)
out_pred = out_pred.assign(_clv=clv).sort_values("_clv", ascending=False).reset_index(drop=True)
out_pred["cum_cust_pct"] = (np.arange(len(out_pred)) + 1) / len(out_pred)
out_pred["cum_clv"] = out_pred["_clv"].cumsum()
total_clv = out_pred["_clv"].sum()
out_pred["cum_clv_pct"] = out_pred["cum_clv"] / total_clv

# Các mốc % CLV
for t in [0.5, 0.7, 0.8, 0.9]:
    share = out_pred.loc[out_pred["cum_clv_pct"] >= t, "cum_cust_pct"].iloc[0]
    print(f"{int(t*100)}% tổng CLV đạt được bởi {share:.1%} khách hàng")

# Biểu đồ Pareto
plt.figure(figsize=(6,4))
plt.plot(out_pred["cum_cust_pct"], out_pred["cum_clv_pct"], lw=2, color="#007AFF")
plt.xlabel("% khách hàng (tích lũy)")
plt.ylabel("% CLV dự báo (tích lũy)")
plt.title("Đường cong Pareto – Phân bổ CLV dự báo (XGBoost)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# Đọc file phân khúc
seg_stats = pd.read_csv(f"{OUT_DIR}/segment_stats_xgb.csv")
seg_stats.rename(columns=str.lower, inplace=True)

# Tính tỷ lệ KH và CLV
seg_stats["share_customers"] = seg_stats["count"] / seg_stats["count"].sum()
seg_stats["share_clv"] = seg_stats["sum"] / seg_stats["sum"].sum()

# Làm tròn & định dạng bảng
seg_stats["share_customers_fmt"] = (seg_stats["share_customers"]*100).round(0).astype(int).astype(str).radd("~").add("%")
seg_stats["share_clv_fmt"] = (seg_stats["share_clv"]*100).round(0).astype(int).astype(str).radd("~").add("%")
table = seg_stats[["segment", "share_customers_fmt", "share_clv_fmt"]]
table.columns = ["Phân khúc", "Tỷ lệ khách hàng", "Tỷ lệ CLV"]

print("\n📊 Phân khúc khách hàng theo CLV:")
print(table.to_string(index=False))

# Biểu đồ CLV trung bình
plt.figure(figsize=(6,4))
plt.bar(seg_stats["segment"], seg_stats["mean"], color=["#007AFF","#00C853","#FFAB00"])
plt.title("Giá trị CLV trung bình theo phân khúc (Low–Mid–High)")
plt.xlabel("Phân khúc")
plt.ylabel("CLV trung bình (dự báo)")
plt.grid(True, axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

import pandas as pd, numpy as np

# Đọc lại file để có biến out_pred
out_pred = pd.read_csv(f"{OUT_DIR}/customer_clv_predictions_xgb.csv")

# Chuẩn bị dữ liệu CLV
clv = out_pred["CLV_pred_final"].clip(lower=0)
out_pred = out_pred.assign(_clv=clv).sort_values("_clv", ascending=False).reset_index(drop=True)
out_pred["cum_cust_pct"] = (np.arange(len(out_pred)) + 1) / len(out_pred)
out_pred["cum_clv"] = out_pred["_clv"].cumsum()
total_clv = out_pred["_clv"].sum()
out_pred["cum_clv_pct"] = out_pred["cum_clv"] / total_clv

# === Từ đây là đoạn tóm tắt ===
n_customers = len(out_pred)
mean_clv = out_pred["_clv"].mean()
median_clv = out_pred["_clv"].median()
p95_clv = out_pred["_clv"].quantile(0.95)
share_80pct = out_pred.loc[out_pred["cum_clv_pct"] >= 0.8, "cum_cust_pct"].iloc[0]

print("\n🧾 Tóm tắt nhanh insight mô hình CLV:")
print(f"- Số khách hàng: {n_customers:,}")
print(f"- CLV trung bình: {mean_clv:,.2f}")
print(f"- CLV trung vị: {median_clv:,.2f}")
print(f"- CLV 95th percentile: {p95_clv:,.2f}")
print(f"- Top {share_80pct*100:.1f}% khách hàng nắm giữ 80% tổng CLV dự báo.")